Bootstrap: docker
From: ubuntu:22.04

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-gimp
    COPYRIGHT Copyright © 2025 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 3.0.4

%environment
    export LANG=C.UTF-8
    export LC_ALL=C.UTF-8
    export PATH="/opt/gimp/squashfs-root:$PATH"

%post
    export DEBIAN_FRONTEND=noninteractive
    apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        libglib2.0-0 \
        libx11-6 libxext6 libxrender1 libxi6 libxfixes3 \
        libxkbcommon0 libxcb1 libxcb-render0 libxcb-shm0 libxcb-image0 libxcb-keysyms1 \
        libgtk-3-0 \
        libatk1.0-0 libgdk-pixbuf-2.0-0 libpango-1.0-0 \
        libjpeg-turbo8 libpng16-16 libtiff5 libwebp7 \
        libfontconfig1 fonts-dejavu-core \
        libgl1 libglu1-mesa wget \
        zlib1g
    apt-get install -y --no-install-recommends curl
    apt-get clean && rm -rf /var/lib/apt/lists/*
    cd /opt/
    wget -nc https://paducahix.mm.fcix.net/gimp/gimp/v3.0/linux/GIMP-3.0.4-x86_64.AppImage
    chmod a+x GIMP-3.0.4-x86_64.AppImage
    ./GIMP-3.0.4-x86_64.AppImage --appimage-extract

%runscript
    exec /opt/squashfs-root/AppRun "$@"
