Bootstrap: docker
From: ubuntu:22.04

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-gimp
    COPYRIGHT Copyright © 2021-2025 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 2.10

%post
    apt-get update && \
    apt-get install -y build-essential gimp
    apt-get clean && rm -rf /var/lib/apt/lists/*

%runscript
    exec gimp "$@"
